### ISSUE TITLE
Do grabber methods need to be overridden?

### ISSUE THREAD

**Issue by nakednous** [VisualComputing/bias.js#1]
I think we should have a second thought on the idea of having to override `track` and `interact`. The current idea is to have the following code within the library (e.g., `GrabberObject`): 

```javascript
@override
interact(event) {
    if (event instanceof KeyEvent)
      keyInteraction(event);
    if (event instanceof TapEvent)
      tapInteraction(event);
    if (event instanceof MotionEvent)
      motionInteraction(event);
}
```
so that a third-party sketch.js willing to implement a callback on the mouse would look like:

```javascript
@override
motion2Interaction(event) {
  // no doubt event is an instanceof Motion2Event .e.g.,
  translate(event.dx, event.dy);
}
```
which seems a bit overkill for a dynamic-type language such as javascript. Perhaps we can bypass `GrabberObject` (completely discarding it) and simply go like this at the sketch:

```javascript
var _mouseShortcut = new Shortcut(LEFT);
var _keyShortcut = new KeyShortcut('a');

interact(event) {
  if (event.shortcut().matches(_mouseShortcut)) {
    // we are sure event is an instanceof Motion2Event .e.g.,
    translate(event.dx, event.dy);
  }
  if (event.shortcut().matches(_keyShortcut)) {
    // we are sure event is an instanceof KeyEvent .e.g.,
    translateXpos();
  }
}
```
what do you guys,  @sechaparroc and @jiapulidoar, think?

**Comment by sechaparroc** [comment]
Both approaches seem valid to me, but I prefer bypassing Grabber Object.

### Using Grabber Object
- A kind of standard is used and it feels a bit more organized
- In both cases interact method should switch between Event types, but with Grabber Object the user doesn't worry about check Types, just put the proper behavior where the methods signature suggest her.
- Unnecesary Type checking.
- Doesn't help at all if Custom Events are implemented
### Bypassing Grabber Object
- Perhaps the user has to get her hands dirty and know a bit better about the event types (which is desirable) 
- User could get disoriented? 
- It is checked only what needs to be checked 
- input.js events and custom events are managed in the same way.

**Comment by nakednous** [comment]
Let's just bypass `GrabberObject` then. Yes, it's nice to treat custom and default events the same way and I prefer by far the syntax?pattern `if (event.shortcut().matches(_otherShortcut)) ` than `if(event instanceof EventClass)`.

@sechaparroc please note that I've just reverted the `interact` and `check` changes (at `bias.js` and `proscene.js` *processing* branches) to reflect this decision.
Please note that
