### ISSUE TITLE
port js examples to bias.js live site

### ISSUE THREAD

**Issue by nakednous** [VisualComputing/bias.js#4]
@jiapulidoar please port when you can the bias.js examples to the [bias.js gh-pages branch](https://github.com/VisualComputing/bias.js/tree/gh-pages) now that we have a working master branch.

**Comment by jiapulidoar** [comment]
Hi @nakednous , bias.js examples are available at [Bias.js live site](https://visualcomputing.github.io/bias.js/) now!

**Comment by nakednous** [comment]
👍 please update once #3 is fixed. I'll close this one too then.

**Comment by jiapulidoar** [comment]
#3  is now fixed and tested.

**Comment by nakednous** [comment]
I reopen the issue as the examples run fine under chromium but not at my firefox (57.0.4 archlinux). @jiapulidoar please test and fix it using the the build 27afd47c798609de435270a8d61c9ff2db4f603d I just pushed.

**Comment by jiapulidoar** [comment]
Hi @nakednous, 

- just fixed the issue with firefox and tested it using the build 27afd47.
I found that the non-standard feature (**MouseEvent.which)** used in the _class MouseAgent_ was causing the issues, This feature is non-standard and is not on a standards track so its behavior was different in chromium and firefox causing the issues in firefox. So I replaced this feature with one of the two standard alternatives to this property _MouseEvent.buttons_  given by the [API](https://developer.mozilla.org/es/docs/Web/API/MouseEvent/which). 

- Lastly, I found an order issue on Bias.js (bias_tree) that I fixed just putting the _class MotionEvent_ before its derived _classes MotionEvent1,2..._ as you can see in the commit d824cf7203466dea058c8e05013f28fb8df097e0.
